spring:
  application:
    name: shokoku-board-article-read-service
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: shokoku-board-article-read-service
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: false
endpoints:
  shokoku-board-article-service:
    url: http://127.0.0.1:9000
  shokoku-board-comment-service:
    url: http://127.0.0.1:9001
  shokoku-board-like-service:
    url: http://127.0.0.1:9002
  shokoku-board-view-service:
    url: http://127.0.0.1:9003
server:
  port: 9005
